name: Setup
description: Install mise tools and Rust dependencies

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v3

    # Workaround: mise-action cache doesn't include ~/.rustup, so
    # Rust components (clippy, rustfmt) are lost on cache restore.
    # See https://github.com/jdx/mise-action/issues/215
    - name: Ensure Rust components are installed
      shell: bash
      run: rustup component add clippy rustfmt

    - name: Get Rust info for cache key
      id: rust-info
      shell: bash
      run: echo "hash=$(mise tool rust --json | jq -j '{tool_options, active_versions}' | shasum -a 256 | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

    - name: Cache cargo registry and build artifacts
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ runner.os }}-${{ steps.rust-info.outputs.hash }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: cargo-${{ runner.os }}-${{ steps.rust-info.outputs.hash }}-
